---
title: "Continuidade dos elencos na NBA"
author: "Cesta de 7"
date: "07/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
```

```{r load data}
conti <- read_html(
  "https://www.basketball-reference.com/friv/continuity.html"
) %>% 
  html_nodes("table") %>% html_table() %>% 
  as.data.frame() %>% as_tibble() %>% 
  pivot_longer(cols = - Season, names_to = "team", values_to = "perc") %>% 
  mutate(perc = str_replace(perc, "%", "") %>% as.numeric(),
         perc = perc/100,
         Season = str_replace_all(Season, "-..", "")) %>% 
  mutate(
    team = 
      case_when(
        team == "ATL" ~ "Atlanta Hawks", team == "BOS" ~ "Boston Celtics",
        team == "CHA" ~ "Charlotte Hornets", team == "CHI" ~ "Chicago Bulls",
        team == "CLE" ~ "Cleveland Cavaliers", team == "DAL" ~ "Dallas Mavericks",
        team == "DEN" ~ "Denver Nuggets", team == "DET" ~ "Detroit Pistons",
        team == "GSW" ~ "Golden State Warriors", team == "HOU" ~ "Houston Rockets",
        team == "IND" ~ "Indiana Pacers", team == "LAC" ~ "Los Angeles Clippers",
        team == "LAL" ~ "Los Angeles Lakers", team == "MEM" ~ "Memphis Grizzlies",
        team == "MIA" ~ "Miami Heat", team == "MIL" ~ "Milwaukee Bucks",
        team == "MIN" ~ "Minnesota Timberwolves", team == "NJN" ~ "New Jersey Nets",
        team == "NOH" ~ "New Orleans Hornets", team == "NYK" ~ "New York Knicks",
        team == "OKC" ~ "Oklahoma City Thunder", team == "ORL" ~ "Orlando Magic",
        team == "PHI" ~ "Philadelphia 76ers", team == "PHO" ~ "Phoenix Suns",
        team == "POR" ~ "Portland Trail Blazers", team == "SAC" ~ "Sacramento Kings",
        team == "SAS" ~ "San Antonio Spurs", team == "TOR" ~ "Toronto Raptors",
        team == "UTA" ~ "Utah Jazz",
        TRUE ~ "Washington Wizards"
      )
  )

years_avb <- 1987:2019
cont_list <- list()

for(i in years_avb){
  df <- read_html(
    paste0(
      "https://www.basketball-reference.com/friv/standings.fcgi?month=6&day=11&year=", 
      i,"&lg_id=NBA"
    )
  ) %>% 
    html_nodes("table") %>% html_table() %>% 
    map(~select(., team = contains("Confe"), W, L)) %>% 
    map_dfr(bind_rows) %>% mutate(year = i)
  
  cont_list[[i - 1986]] <- df
  Sys.sleep(5)
}

perf_df <- cont_list %>% 
  map_dfr(bind_rows) %>% filter(!is.na(W)) %>% 
  mutate(
    pl = case_when(
      str_detect(team, "[:punct:]") ~ "PL",
      TRUE                          ~ "Nope"
    )
  ) %>% 
  mutate(
    team = str_remove(team, "[:punct:]"),
    year = as.character(year)
  ) %>% 
  mutate(
    team = case_when(
      team %in% c("Charlotte Bobcats", "New OrleansOklahoma City Hornets") ~ "Charlotte Hornets", 
      team == "New Orleans Pelicans" ~  "New Orleans Hornets", 
      team == "Washington Bullets" ~ "Washington Wizards",
      team == "Vancouver Grizzlies" ~ "Memphis Grizzlies",
      TRUE ~ team
    )
  )
read_html("https://www.basketball-reference.com/leagues/") %>% 
  html_node("table") %>% html_table() %>% as.data.frame() %>%
  .[,c(1,3)] %>% select("year" = "", "champ" = ".1") %>% 
  mutate(year = str_replace_all(year, "-..", ""))
  
final_df <- conti %>% 
  left_join(
    perf_df,
    by = c("team" = "team", "Season" = "year")
  )

```

```{r explore}
conti %>% 
  ggplot(aes(x = Season, y = team, fill = perc)) +
  geom_tile() 

conti %>% 
  group_by(Season) %>% 
  filter(dense_rank(perc) <= 3 | dense_rank(desc(perc)) <= 3) %>% 
  ungroup() %>% mutate(top_bot = ifelse(perc > .5, "top", "bottom")) %>% 
  group_by(Season, top_bot) %>% 
  summarise(soma = mean(perc)) %>% 
  
  ggplot(aes(x = Season, y = soma, group = top_bot)) +
  geom_line()

final_df %>% drop_na() %>% 
  ggplot(aes(x = Season, y = W/L + perc)) +
  geom_point()
```

